services:
  db:
    image: mysql:8
    container_name: ecommerce-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test_ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ecommerce-back
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 3000
      GRPC_URL: 0.0.0.0:50051
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: ""
      DB_NAME: test_ecommerce
    ports:
      - "3000:3000"
      - "50051:50051"

volumes:
  mysql_data:
